BX1 : BUGFIX obsiot-power BX1 : Support Debian9

diff --git a/build_ramdisk/etc.stretch/init.d/obsiot-power b/build_ramdisk/etc.stretch/init.d/obsiot-power
--- a/build_ramdisk/etc.stretch/init.d/obsiot-power
+++ b/build_ramdisk/etc.stretch/init.d/obsiot-power
@@ -62,11 +62,41 @@ VERBOSE=yes
 
 [ -f /etc/default/openblocks ] && . /etc/default/openblocks
 
+case $MODEL in
+obsvx*)
+	POWER_USB=366
+	POWER_AC=367
+	POWER_DC=365
+	;;
+obsbx1)
+	POWER_USB=40
+	POWER_AC=41
+	POWER_DC=42
+	;;
+obsgem*)
+	POWER_USB=113
+	POWER_AC=110
+	POWER_DC=114
+	;;
+*)
+	exit 1
+	;;
+esac
+
 #
 # Function that starts the daemon/service
 #
 do_start()
 {
+	if [ ! -d /sys/class/gpio/gpio${POWER_USB} ]; then
+		echo ${POWER_USB} > /sys/class/gpio/export
+	fi
+	if [ ! -d /sys/class/gpio/gpio${POWER_AC} ]; then
+		echo ${POWER_AC} > /sys/class/gpio/export
+	fi
+	if [ ! -d /sys/class/gpio/gpio${POWER_DC} ]; then
+		echo ${POWER_DC} > /sys/class/gpio/export
+	fi
 	# Return
 	#   0 if daemon has been started
 	#   1 if daemon was already running
@@ -104,124 +134,55 @@ do_stop()
 	[ "$?" = 2 ] && return 2
 	# Many daemons don't delete their pidfiles when they exit.
 	rm -f $PIDFILE
+	if [ -d /sys/class/gpio/gpio${POWER_USB} ]; then
+		echo ${POWER_USB} > /sys/class/gpio/unexport
+	fi
+	if [ -d /sys/class/gpio/gpio${POWER_AC} ]; then
+		echo ${POWER_AC} > /sys/class/gpio/unexport
+	fi
+	if [ -d /sys/class/gpio/gpio${POWER_DC} ]; then
+		echo ${POWER_DC} > /sys/class/gpio/unexport
+	fi
 	return "$RETVAL"
-}
-
-#
-# Function that sends a SIGHUP to the daemon/service
-#
-do_reload() {
-	#
-	# If the daemon can reload its configuration without
-	# restarting (for example, when it is sent a SIGHUP),
-	# then implement that here.
-	#
-	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
-	return 0
 }
 
 case "$1" in
   start)
-	case $MODEL in
-	obsa*|obs600)
-		echo "Not supported."
-		exit 1
-		;;
-	obsvx*)
-		if [ ! -d /sys/class/gpio/gpio366 ]; then
-			echo 366 > /sys/class/gpio/export
-		fi
-		if [ ! -d /sys/class/gpio/gpio367 ]; then
-			echo 367 > /sys/class/gpio/export
-		fi
-		if [ ! -d /sys/class/gpio/gpio365 ]; then
-			echo 365 > /sys/class/gpio/export
-		fi
-		;;
-	obsgem*)
-		if [ ! -d /sys/class/gpio/gpio113 ]; then
-			echo 113 > /sys/class/gpio/export
-		fi
-		if [ ! -d /sys/class/gpio/gpio110 ]; then
-			echo 110 > /sys/class/gpio/export
-		fi
-		if [ ! -d /sys/class/gpio/gpio114 ]; then
-			echo 114 > /sys/class/gpio/export
-		fi
-		;;
-	obsbx1)
-		if [ ! -d /sys/class/gpio/gpio40 ]; then
-			echo 40 > /sys/class/gpio/export
-		fi
-		if [ ! -d /sys/class/gpio/gpio41 ]; then
-			echo 41 > /sys/class/gpio/export
-		fi
-		if [ ! -d /sys/class/gpio/gpio42 ]; then
-			echo 42 > /sys/class/gpio/export
-		fi
-		;;
-	esac
 	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
 	do_start
 	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+		0) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		*) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
 	esac
 	;;
   stop)
-	case $MODEL in
-	obsa*|obs600)
-		echo "Not supported."
-		exit 1
-		;;
-	obsvx*)
-		if [ -d /sys/class/gpio/gpio366 ]; then
-			echo 366 > /sys/class/gpio/unexport
-		fi
-		if [ -d /sys/class/gpio/gpio367 ]; then
-			echo 367 > /sys/class/gpio/unexport
-		fi
-		if [ -d /sys/class/gpio/gpio365 ]; then
-			echo 365 > /sys/class/gpio/unexport
-		fi
-		;;
-	obsgem*)
-		if [ -d /sys/class/gpio/gpio113 ]; then
-			echo 113 > /sys/class/gpio/unexport
-		fi
-		if [ -d /sys/class/gpio/gpio110 ]; then
-			echo 110 > /sys/class/gpio/unexport
-		fi
-		if [ -d /sys/class/gpio/gpio114 ]; then
-			echo 114 > /sys/class/gpio/unexport
-		fi
-		;;
-	obsbx1)
-		if [ -d /sys/class/gpio/gpio40 ]; then
-			echo 40 > /sys/class/gpio/unexport
-		fi
-		if [ -d /sys/class/gpio/gpio41 ]; then
-			echo 41 > /sys/class/gpio/unexport
-		fi
-		if [ -d /sys/class/gpio/gpio42 ]; then
-			echo 42 > /sys/class/gpio/unexport
-		fi
-		;;
-	esac
 	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
-	if [ "$MODEL" = "obsbx1" ]; then
-		echo 1 > /sys/class/misc/watchdog/disable
-	fi
-	if [ "$MODEL" != "obsbx1" ]; then
-		do_stop
-	fi
+	do_stop
 	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+		0) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		*) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
+	;;
+  restart)
+	log_daemon_msg "Restarting $DESC" "$NAME"
+	do_stop
+	case "$?" in
+	0)
+		do_start
+		case "$?" in
+			0) log_end_msg 0 ;;
+			1) log_end_msg 1 ;; # Old process is still running
+			*) log_end_msg 1 ;; # Failed to start
+		esac
+        ;;
+	*)
+		# Failed to stop
+		log_end_msg 1
+		;;
 	esac
 	;;
   *)
-	echo "Usage: $SCRIPTNAME {start|stop}" >&2
+	echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
 	exit 3
 	;;
 esac
