GEM1: fix modem control

diff --git a/build_ramdisk/etc.buster.obsgem1/init.d/nitz b/build_ramdisk/etc.buster.obsgem1/init.d/nitz
--- a/build_ramdisk/etc.buster.obsgem1/init.d/nitz
+++ b/build_ramdisk/etc.buster.obsgem1/init.d/nitz
@@ -47,6 +47,42 @@ ATCMD="/usr/sbin/atcmd -d /dev/ttyMODEM0"
 # Read configuration variable file if it is present
 [ -r /etc/default/openblocks ] && . /etc/default/openblocks
 
+set_time_ehs6(){
+	# check builtin MODEM
+	echo -n "nitz: 3G modem power on : "
+	$ATCMD PON
+	if [ ! -e /dev/ttyMODEM0 ]; then
+		echo "fail"
+		exit 1
+	fi
+	echo "done"
+
+	echo -n "nitz: check SIM card : "
+	# check SIM card
+	val=`$ATCMD CCID`
+	if [ $? == 255 ]; then
+		echo "fail"
+#		$ATCMD POFF
+		exit 1
+	fi
+	echo "done"
+
+	echo -n "nitz: time synchronization : "
+	val=`$ATCMD SIND`
+	if [ $? == 255 ]; then
+		echo "fail"
+#		$ATCMD POFF
+		exit 1
+	fi
+	echo "done"
+
+	# set NITZ to SYSTEM
+	date "$val" --utc
+	# set SYSTEM to RTC
+	hwclock --systohc
+#	$ATCMD POFF
+}
+
 set_time_u200(){
 	# check builtin MODEM
 	echo -n "nitz: 3G modem power on : "
@@ -63,6 +99,7 @@ set_time_u200(){
 	val=`$ATCMD CCID`
 	if [ $? == 255 ]; then
 		echo "fail"
+#		$ATCMD POFF
 		exit 1
 	fi
 	echo "done"
@@ -71,6 +108,7 @@ set_time_u200(){
 	val=`$ATCMD CCLK`
 	if [ $? == 255 ]; then
 		echo "fail"
+#		$ATCMD POFF
 		exit 1
 	fi
 	echo "done"
@@ -79,51 +117,120 @@ set_time_u200(){
 	date "$val"
 	# set SYSTEM to RTC
 	hwclock --systohc
+#	$ATCMD POFF
 }
 
 set_time_kym11(){
 	echo "done"
 }
 
+set_time_s710(){
+	echo "done"
+}
+
 case "$1" in
   start)
-	if [ "$MODEL" == "obsvx2" ]; then
-		if [ -x /usr/sbin/sshd ] ; then
-			dpkg-reconfigure openssh-server
-		fi
-	fi
-	# initialize LED, INIT
-	GPIOPATH="/sys/class/gpio"
-	echo 98 > $GPIOPATH/export	# LED red
-	[ -d $GPIOPATH/gpio98 ] && echo out > $GPIOPATH/gpio98/direction
-	echo 99 > $GPIOPATH/export	# LED green
-	[ -d $GPIOPATH/gpio99 ] && echo out > $GPIOPATH/gpio99/direction
-	echo 100 > $GPIOPATH/export	# LED blue
-	[ -d $GPIOPATH/gpio100 ] && echo out > $GPIOPATH/gpio100/direction
-	echo 76 > $GPIOPATH/export	# INIT SW
-	[ -d $GPIOPATH/gpio76 ] && echo both > $GPIOPATH/gpio76/edge
+	dpkg-reconfigure openssh-server
 
 	MODEM=`/usr/sbin/obsiot-modem.sh`
-	if [ "$MODEM" != "none" ]; then
-		obsvx1-modem init
-		[ "$MODEM" == "S710" ] && obsvx1-modem power low
-		atcmd PON
+	POW="488"
+	RST="490"
+	case $MODEM in
+	U200E|UM04)
+		echo ${POW} > $GPIOPATH/export	# 3G modem power
+		echo high > $GPIOPATH/gpio${POW}/direction
+		echo ${RST} > $GPIOPATH/export	# 3G reset
+		echo high > $GPIOPATH/gpio${RST}/direction
+		;;
+	KYM11|S710E)
+		echo ${RST} > $GPIOPATH/export	# 3G reset
+		echo high > $GPIOPATH/gpio${RST}/direction
+		echo ${POW} > $GPIOPATH/export	# 3G modem power
+		echo low > $GPIOPATH/gpio${POW}/direction
+		if [ ! -e /dev/ttyMODEM0 ]; then
+			echo 1 > $GPIOPATH/gpio${POW}/value
+			sleep 4
+			echo 0 > $GPIOPATH/gpio${POW}/value
+			sleep 20
+		fi
+		;;
+	EHS6|S710)
+		POW="96"
+		RST="95"
+		echo ${POW} > $GPIOPATH/export	# 3G modem power
+		echo low > $GPIOPATH/gpio${POW}/direction
+		echo ${RST} > $GPIOPATH/export	# 3G reset
+		echo low > $GPIOPATH/gpio${RST}/direction
+		;;
+	U200)
+		POW="96"
+		RST="95"
+		echo ${POW} > $GPIOPATH/export	# 3G modem power
+		echo high > $GPIOPATH/gpio${POW}/direction
+		echo ${RST} > $GPIOPATH/export	# 3G reset
+		echo low > $GPIOPATH/gpio${RST}/direction
+		;;
+	*)
+		;;
+	esac
+
+	# set LED, INIT
+	echo 98 > $GPIOPATH/export	# LED red
+	echo out > $GPIOPATH/gpio98/direction
+	echo 99 > $GPIOPATH/export	# LED green
+	echo out > $GPIOPATH/gpio99/direction
+	echo 100 > $GPIOPATH/export	# LED blue
+	echo out > $GPIOPATH/gpio100/direction
+	echo 76 > $GPIOPATH/export	# INIT SW
+	echo both > $GPIOPATH/gpio76/edge
+
+	# check init sw
+	grep -q 'noflashcfg=1' /proc/cmdline
+	if [ $? == 0 ]; then
+		echo "nitz: push INIT switch"
+		exit 1
 	fi
+
+	case $MODEM in
+	EHS6)
+		set_time_ehs6
+		;;
+	U200|S710)
+		set_time_u200
+		;;
+	S710E)
+		set_time_s710
+		;;
+	U200E|KYM11|UM04|S710E|none)
+		echo "nitz: skipped time synchronization"
+		;;
+	*)
+		echo "fail"
+		exit 1
+	esac
+
+	rfkill unblock bluetooth
+	exit 0
 	;;
   stop)
 	;;
   settime)
-	MODEM=`/usr/sbin/obsiot-modem.sh`
-	case $MODEM in
-	U200*)
-		set_time_u200
-	;;
-	KYM11)
-		set_time_kym11
-	;;
-	*)
-	;;
-	esac
+		MODEM=`/usr/sbin/obsiot-modem.sh`
+		case $MODEM in
+		EHS6)
+			set_time_ehs6
+		;;
+		U200*)
+			set_time_u200
+		;;
+		KYM11)
+		;;
+		S710*)
+			set_time_s710
+		;;
+		*)
+		;;
+		esac
 	;;
   *)
 	echo "Usage: $SCRIPTNAME {start|stop|settime}" >&2
@@ -131,4 +238,3 @@ case "$1" in
 	;;
 esac
 
-exit 0
